name: Oracle ARM Grabber
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # สั่งรันทุก 30 นาที

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Oracle Stack
        uses: oracle-actions/run-resource-manager-job@v1
        with:
          tenancy: ${{ secrets.OCI_TENANCY_ID }}
          user: ${{ secrets.OCI_USER_ID }}
          key: ${{ secrets.OCI_PRIVATE_KEY }}
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          region: ${{ secrets.OCI_REGION }}
          stack_id: ${{ secrets.OCI_STACK_ID }}
          operation: APPLY
